{
 "title": "My Dashboard",
 "panels": [
  {
   "title": "Article custom metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(__name__) (product_count_total)",
     "legendFormat": "Article creation count"
    },
    { "expr": "active_article_count", "legendFormat": "Active article count" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[5m])) by (le, method, endpoint)) * 1000",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, endpoint, http_status) (rate(request_count_total{endpoint=\"/articles\"}[1m]))",
     "legendFormat": "articles"
    },
    {
     "expr": "sum by(method, endpoint, http_status) (rate(request_count_total{endpoint=\"/articles/popular\"}[1m]))",
     "legendFormat": "popular"
    },
    {
     "expr": "sum by(method, endpoint, http_status) (rate(request_count_total{endpoint=\"/articles/search\"}[1m]))",
     "legendFormat": "search"
    },
    {
     "expr": "sum by(method, endpoint, http_status) (rate(request_count_total{endpoint=\"/metrics\"}[1m]))",
     "legendFormat": "metrics"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    { "expr": "memory_usage ", "legendFormat": "Memory usage" }
   ]
  },
  {
   "title": "Total Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req/ms" } },
   "targets": [
    {
     "expr": "sum by (method, endpoint, http_status) (rate(request_count_total[1m])) * 1000",
     "legendFormat": "{{method}} {{endpoint}} {{http_status}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "codes/ms" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(status_code_count_total[1m])) * 1000",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    { "expr": "cpu_usage" }
   ]
  }
 ]
}