{
 "title": "Loki Logs Dashboard",
 "panels": [
  {
   "title": "All Info Lines",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"} |= `INFO`"
    }
   ]
  },
  {
   "title": "Delete debug information",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"} |= `DELETE` |= \"DEBUG\" | logfmt --strict"
    }
   ]
  },
  {
   "title": "Logs over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"DEBUG\" [1h])\r\n\r\n",
     "legendFormat": "Debug"
    },
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"INFO\" [1h])\r\n",
     "legendFormat": "Info"
    },
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"ERROR\" [1h])",
     "legendFormat": "Error"
    },
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"WARN\" [1h])",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Messages pie",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"INFO\" [3h])",
     "legendFormat": "Info"
    },
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"DEBUG\" [3h])",
     "legendFormat": "Debug"
    },
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"ERROR\" [3h])",
     "legendFormat": "Error"
    },
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"WARN\" [3h])",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{job=\"varlogs\"} |= `DEBUG` |= `CPU`"
    }
   ]
  }
 ]
}