{
 "title": "Articles API Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Server Errors occur often",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      {
       "id": "a52fdc99",
       "operator": ">",
       "scope": "span",
       "tag": "http.status_code",
       "value": [ "500" ],
       "valueType": "int"
      }
     ],
     "limit": 20,
     "query": "{ span.http.status_code >= 500 } | count() > 2\r\n",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "High latency requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "26af5070", "operator": "=", "scope": "span" },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "0.5",
       "valueType": "duration"
      },
      { "id": "duration-type", "value": "trace" }
     ],
     "limit": 20,
     "query": "{ traceDuration > 0.5s } | count() > 2\r\n",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({resource.service.name=\"articles-api\"}[5m])) by (method)",
     "filters": [
      { "id": "3a37684f", "operator": "=", "scope": "span" }
     ],
     "legendFormat": "{{method}}",
     "limit": 20,
     "query": "{resource.service.name=\"articles-api\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate({resource.service.name=\"articles-api\"}[5m])) by (le))",
     "filters": [
      { "id": "2445f450", "operator": "=", "scope": "span" }
     ],
     "legendFormat": "P95 Latency",
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Top Slow Endpoints",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, avg(rate({resource.service.name=\"articles-api\"}[5m])) by (endpoint))",
     "filters": [
      { "id": "b462c591", "operator": "=", "scope": "span" }
     ],
     "legendFormat": "{{endpoint}}",
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({resource.service.name=\"articles-api\"}[5m])) by (instance)",
     "filters": [
      { "id": "f6af6557", "operator": "=", "scope": "span" }
     ],
     "legendFormat": "{{instance}}",
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}