version: '3.8'

services:
  python-server:
    build: .
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - my_app_logs:/var/log/my_app
      - migrations_volume:/usr/src/app/migrations
    ports:
      - "${PYTHON_SERVER_PORT}:8080"
    environment:
      - FLASK_APP=openapi_server.__main__:app
    depends_on:
      - prometheus
      - promtail
      - loki
      - postgres
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    depends_on:
      - promtail
    networks:
      - monitoring

  loki:
    image: grafana/loki
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - promtail
    networks:
      - monitoring

  promtail:
    image: grafana/promtail
    ports:
      - "${PROMTAIL_PORT}:9080"
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - my_app_logs:/var/log/my_app
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitoring

  tempo:
    image: grafana/tempo
    ports:
      - "4317:4317"
      - "3200:3200"
    volumes:
      - ./tempo-config.yml:/etc/tempo/tempo-config.yaml
    command: -config.file=/etc/tempo/tempo-config.yaml - distributor.log_received_spans.enabled -log.level=debug
    networks:
      - monitoring

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: articles_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  my_app_logs:
  grafana-storage:
  postgres_data:
  migrations_volume:
