name: Test Application

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for tests
        run: |
          docker compose -f docker-compose.test.yml up --build -d 
          docker compose exec -T python-server pytest --maxfail=1 --disable-warnings -q

      - name: Run tests in Docker container
        run: docker run my-flask-app-test
